services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_PROXY_HOPS=1
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - WEBHOOK_URL=https://${NGROK_DOMAIN}/
    volumes:
      - ./n8n-data:/home/node/.n8n
    command: start
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-sidecar
    restart: always
    command: "http n8n:5678 --domain=${NGROK_DOMAIN}"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - n8n
